/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hessin.graphic;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Rect rect = new Rect();
        assertTrue("someLibraryMethod should return 'true'", rect != null);
    }
}
